# NumPY ( Matrix)

Numpy Crash Course

In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
import sys
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

# Create a list

In [5]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

# Below code we are convering list to array

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

# np. important functions 

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [14]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [19]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
np.arange(-20,5)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4])

In [21]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [23]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [24]:
np.zeros(10) # Parameter tuning

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros(10,int)  # Hyperparameter Tuning

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.zeros(1,2)

TypeError: Cannot interpret '2' as a data type

In [28]:
np.zeros((2,2), dtype =int)

array([[0, 0],
       [0, 0]])

In [29]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones(2,2)

TypeError: Cannot interpret '2' as a data type

In [31]:
np.ones(3)

array([1., 1., 1.])

In [32]:
np.ones(3, int)

array([1, 1, 1])

In [34]:
np.ones((2,3) , int)

array([[1, 1, 1],
       [1, 1, 1]])

In [36]:
np.two((5,6), int)

AttributeError: module 'numpy' has no attribute 'two'