In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

# What is Numpy? 
    NumPy is the fundamental package for scientific computing in Python. 
 
 
    It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types 

# Creating Numpy array 

In [3]:
np.array([2,4,56,422,32,1]) # iD array

array([  2,   4,  56, 422,  32,   1])

In [4]:
a = np.array([2,4,56,422,32,1]) # Vector
a

array([  2,   4,  56, 422,  32,   1])

In [5]:
type(a)

numpy.ndarray

In [6]:
# 2D array ( Matrix) using list
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# 2D array using tuple
np.array(([1,2,3],[4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#  3 D ---- # Tensor 
np.array(([1,2,3,4],[5,6,6,7],[8,9,3,2]))

array([[1, 2, 3, 4],
       [5, 6, 6, 7],
       [8, 9, 3, 2]])

# dtype 
The desired data-type for the array. If not given, then the type willbe determined as the 
minimum type required to hold the objects in thesequence. 

In [9]:
np.array([11,23,44], dtype= float)

array([11., 23., 44.])

In [10]:
np.array([11,23,0], dtype= bool)  # Here True becoz , python treats Non -zero

array([ True,  True, False])

In [11]:
np.array((2.5,3,15), dtype = complex)

array([ 2.5+0.j,  3. +0.j, 15. +0.j])

# Numpy Arrays Vs Python Sequences 
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). 
Changing the size of an ndarray will create a new array and delete the original. 
The elements in a NumPy array are all required to be of the same data type, and thus will be 
the same size in memory. 
NumPy arrays facilitate advanced mathematical and other types of operations on large 
numbers of data. Typically, such operations are executed more efficiently and with less code 
than is possible using Python’s built-in sequences. 
A growing plethora of scientific and mathematical Python-based packages are using NumPy 
arrays; though these typically support Python-sequence input, they convert such input to 
NumPy arrays prior to processing, and they often output NumPy arrays. 

 # 1.Arrange
 arange can be called with a varying number of positional arguments

In [12]:
np.arange(5,15) # 5-included , 15(n-1) - last one got excluded 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
np.arange(0,20,2) #strides ---> Alternate numbers 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# 2. reshape 

In [14]:
np.arange(1,11) # with our reshaping 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(1,11).reshape(2,5) # converted 2 rows and 5 columns 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
np.arange(1,11).reshape(5,2) # converted 5 rows and 2 columns 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# ones & Zeros

In [17]:
np.ones(2 )

array([1., 1.])

In [18]:
np.ones(5, dtype = int) # 1D array with 5 elements of dtype of integer.

array([1, 1, 1, 1, 1])

In [19]:
np.ones([2,5],dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.zeros((5,2),dtype = int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [21]:
# Another Type ---> random() 
np.random((2,5))

TypeError: 'module' object is not callable

In [22]:
np.random.random((2,5), datatype = int)

TypeError: random() got an unexpected keyword argument 'datatype'

In [23]:
np.random.random((2,5)) # first random is module and second one is Function()

array([[0.86266749, 0.16421309, 0.06673429, 0.98410814, 0.0823164 ],
       [0.32474186, 0.99664287, 0.19920786, 0.74613531, 0.53671227]])

In [25]:
## np.random.randint((4,15)) # Randint will give any 4 numbers between 0 to 15

# linspace

In [26]:
np.linspace(-10,10)

array([-10.        ,  -9.59183673,  -9.18367347,  -8.7755102 ,
        -8.36734694,  -7.95918367,  -7.55102041,  -7.14285714,
        -6.73469388,  -6.32653061,  -5.91836735,  -5.51020408,
        -5.10204082,  -4.69387755,  -4.28571429,  -3.87755102,
        -3.46938776,  -3.06122449,  -2.65306122,  -2.24489796,
        -1.83673469,  -1.42857143,  -1.02040816,  -0.6122449 ,
        -0.20408163,   0.20408163,   0.6122449 ,   1.02040816,
         1.42857143,   1.83673469,   2.24489796,   2.65306122,
         3.06122449,   3.46938776,   3.87755102,   4.28571429,
         4.69387755,   5.10204082,   5.51020408,   5.91836735,
         6.32653061,   6.73469388,   7.14285714,   7.55102041,
         7.95918367,   8.36734694,   8.7755102 ,   9.18367347,
         9.59183673,  10.        ])

In [27]:
np.linspace(-10,10,10)  # here: lower range,upper range ,number of items to gen

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [29]:
np.linspace(2,15,10)

array([ 2.        ,  3.44444444,  4.88888889,  6.33333333,  7.77777778,
        9.22222222, 10.66666667, 12.11111111, 13.55555556, 15.        ])

# identity 
indentity matrix is that diagonal items will be ones and evrything will be zeros 

In [30]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.identity(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [32]:
np.identity(5, dtype = bool)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

# Array Attributes

In [33]:
import numpy as np
a1 = np.arange(5) 
print(a1)

[0 1 2 3 4]


In [34]:
a2 = np.arange(25, dtype = int).reshape(5,5) # Matrix
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
import numpy as np
a3 = np.arange(16, dtype = float).reshape(4,2,2) #3D array
a3

array([[[ 0.,  1.],
        [ 2.,  3.]],

       [[ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.]],

       [[12., 13.],
        [14., 15.]]])

In [42]:
import numpy as np
a3 = np.arange(16, dtype = float).reshape(2,4,2) #3D array
a3

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]]])

In [43]:
a1, a2 ,a3

(array([0, 1, 2, 3, 4]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 array([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.]],
 
        [[ 8.,  9.],
         [10., 11.],
         [12., 13.],
         [14., 15.]]]))

In [44]:
a1.ndim, a2.ndim , a3.ndim  # ndim To findout given arrays number of dimensions 

(1, 2, 3)

In [45]:
a1.shape , a2.shape, a3.shape  # Shape gives each item consist of no.of rows and np.of column 

((5,), (5, 5), (2, 4, 2))

In [46]:
a1.size, a2.size, a3.size #size gives number of items 

(5, 25, 16)

In [48]:
a1.itemsize, a2.itemsize,a3.itemsize #item size Memory occupied by the item 

(8, 8, 8)

In [49]:
a1, a2, a3

(array([0, 1, 2, 3, 4]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 array([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.]],
 
        [[ 8.,  9.],
         [10., 11.],
         [12., 13.],
         [14., 15.]]]))

In [50]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype) # dtype of the give array

int64
int64
float64


# Changing Data Type

In [51]:
a2.astype(float)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [52]:
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
a2.dtype

dtype('int64')

In [54]:
#astype 
 
x = np.array([33, 22, 2.5]) 
x 

array([33. , 22. ,  2.5])

In [55]:
x.astype(int)

array([33, 22,  2])

# Array Operations

In [56]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1, a2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [57]:
a1+a2 # Vector Opearations  addition

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [58]:
a1-a2 # Vector  Operation subtraction

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [59]:
a2-a1

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [60]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [61]:
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

a1**2

In [62]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [63]:
a1/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [64]:
a1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

# Relational Operators 
The relational operators are also known as comparison operators, their main function is to 
return either a true or false based on the value of operands

In [65]:
a1 > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [66]:
a1<2

array([[ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

# Array Functions

In [67]:
k1 =np.random.random((3,3))
k1

array([[0.58290451, 0.18562964, 0.20566728],
       [0.8541891 , 0.6170293 , 0.96698128],
       [0.29639652, 0.89024347, 0.99355472]])

In [68]:
k1= np.round(k1*100)
k1

array([[58., 19., 21.],
       [85., 62., 97.],
       [30., 89., 99.]])

In [69]:
np.max(k1)

np.float64(99.0)

In [70]:
np.min(k1)

np.float64(19.0)

In [71]:
np.amax(k1)

np.float64(99.0)

In [72]:
np.sum(k1)

np.float64(560.0)

In [73]:
np.prod(k1)

np.float64(3127013057183400.0)

# In Numpy 0 = column and 1 = row

In [78]:
k1

array([[58., 19., 21.],
       [85., 62., 97.],
       [30., 89., 99.]])

In [79]:
 #  if we want maximum of every row 
np.max(k1, axis = 1)

array([58., 97., 99.])

In [80]:
 # maximum of every column 
 
np.max(k1, axis = 0) 

array([85., 89., 99.])

In [82]:
#  if we want min of every row 
np.min(k1, axis =1)

array([19., 62., 30.])

In [83]:
# product of every column 
np.prod(k1, axis=1)

array([ 23142., 511190., 264330.])

In [84]:
np.prod(k1,axis=0)

array([147900., 104842., 201663.])

# Statistics related fuctions

# mean

In [86]:
k1

array([[58., 19., 21.],
       [85., 62., 97.],
       [30., 89., 99.]])

In [87]:
np.mean(k1)

np.float64(62.22222222222222)

In [91]:
k1.mean(axis = 0) , k1.mean(axis =1)

(array([57.66666667, 56.66666667, 72.33333333]),
 array([32.66666667, 81.33333333, 72.66666667]))

In [92]:
np.median(k1)

np.float64(62.0)

In [93]:
np.std(k1)

np.float64(30.589677916933493)

In [94]:
np.std(k1, axis = 0)

array([22.45489306, 28.82514335, 36.30733014])

#   Trignometry Functions 

In [95]:
np.sin(k1)  # sin of k1

array([[ 0.99287265,  0.14987721,  0.83665564],
       [-0.17607562, -0.7391807 ,  0.37960774],
       [-0.98803162,  0.86006941, -0.99920683]])

In [96]:
k1.sin()

AttributeError: 'numpy.ndarray' object has no attribute 'sin'

In [97]:
np.cos(k1)

array([[ 0.11918014,  0.98870462, -0.54772926],
       [-0.98437664,  0.67350716, -0.92514754],
       [ 0.15425145,  0.51017704,  0.03982088]])

In [98]:
np.tan(k1)

array([[  8.33085685,   0.15158947,  -1.52749853],
       [  0.17887017,  -1.09750978,  -0.4103213 ],
       [ -6.4053312 ,   1.68582537, -25.09253498]])

 # Dot product 

In [103]:
s2 = np.arange(12).reshape(3,4) 
s3 = np.arange(12,24).reshape(4,3) 
s2, s3

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]))

In [105]:
np.dot(s2,s3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [106]:
np.exp(s2)  # Log and Exponents 

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

# round / floor /ceil

# 1. round 
    The numpy.round() function rounds the elements of an array to the nearest integer or to the specified number of decimals. 

In [109]:
np.round(12.5)

np.float64(12.0)

In [110]:
#  Round to the nearest integer 
arr = np.array([1.2,2.7,3.5,4.9])
roundoff_arr = np.round(arr)
print(roundoff_arr)

[1. 3. 4. 5.]


In [112]:
#  Round to two decimals 
arr = np.array((1.2245,2.658,4.693,3.332))
arr_roundofftt0twodeci = np.round(arr, decimals =2)
print(arr_roundofftt0twodeci)

[1.22 2.66 4.69 3.33]


In [114]:
x = np.random.random((2,3))
x

array([[0.81791183, 0.91782158, 0.97552308],
       [0.4810668 , 0.25323656, 0.26883296]])

In [117]:
np.round(x *100)

array([[82., 92., 98.],
       [48., 25., 27.]])

In [120]:
np.round(np.random.random((2,3))*100)

array([[91., 92., 71.],
       [ 6., 14., 36.]])

# 2. Floor
    The numpy.floor() function returns the largest integer less than or equal to each       element of an array. 

In [122]:
arr  = np.array([1.2, 3.4,3.6,7.2,5.5])
arr
np.floor(arr)

array([1., 3., 3., 7., 5.])

In [125]:
np.floor_divide(arr ,1)

array([1., 3., 3., 7., 5.])

In [131]:
np.floor(np.random.random((2,3))*100) # gives the smallest integer ex :6.8 = 6

array([[69.,  3., 31.],
       [77., 34.,  9.]])

# Ceil
    The numpy.ceil() function returns the smallest integer greater than or equal to each element of an array. 

In [132]:
arr = np.array([1.2,2.5,3.3,4.6,5.5])
np.ceil(arr)

array([2., 3., 4., 5., 6.])

In [134]:
np.ceil(np.random.random((2,3))*10)  # gives highest integer ex : 7.8 = 8

array([[7., 9., 2.],
       [3., 5., 9.]])

# Indexing and slicing

In [136]:
p1 = np.arange(10)
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
p2 = np.arange(12).reshape(3,4)
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [140]:
p3 = np.arange(8).reshape(2,2,2)
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Indexing on 1D array 

In [141]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
print(p1[-1]) , print(p1[2:]), print(p1[1::2])

9
[2 3 4 5 6 7 8 9]
[1 3 5 7 9]


(None, None, None)

# indexing on 2D array 

In [146]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [147]:
p2[0]

array([0, 1, 2, 3])

In [149]:
p2[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [152]:
p2 # fetching desired element : 6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [154]:
print(p2[1,2])  # here 1 = row(second) , 2= column(third) , becoz it starts from zero

6


In [159]:
#  in p2 fetching desired element : 11
print (p2[-1,-1]) # row -1 and column =-1 both from backwords
# or
print(p2[(2,3)]) # row =2 , column =3


11
11


In [160]:
 # fetching desired element : 
 
p2[1,0] # row =1 , column =0 

np.int64(4)

#   indexing on 3D ( Tensors) 

In [161]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [163]:
# fetching desired element : 5  
# EXPLANATION :Here 3D is consists of 2 ,2D array , so Firstly we take 1 because our desired is 
# 5 is in second matrix which is 1 .and 1 row so 0 and second column so 1 
p3[1,0,1]

np.int64(5)

In [165]:
# fetching desired element : 2 
    # EXPLANATION :Here firstly we take 0 because our desired is 2, is in first matrix which is 0 . 
# and 2 row so 1 and first column so 0 
p3[0,1,0] 

np.int64(2)

# Slicing 
    Fetching Multiple items

In [166]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
p1[2:5]

array([2, 3, 4])

In [168]:
# Alternate (same as python) 
 
p1[2:5:2] 

array([2, 4])

    #Slicing on 2D

In [169]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [176]:
p2[0:1]

array([[0, 1, 2, 3]])

In [178]:
p2[0,:] #fetching total First row 

array([0, 1, 2, 3])

    # fetching total third column 

In [179]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
p2[:,2] #EXPLANATION :Here we want all rows so (:) , and we want 3rd column so 2

array([ 2,  6, 10])

In [185]:
#  fetch 5,6 and 9,10 in 
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [188]:
p2[1:3]  # for rows

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [189]:
p2[1:3,1:3]  # For columns

array([[ 5,  6],
       [ 9, 10]])

In [192]:
# fetch 0,3 and 8,11 
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [194]:
p2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [196]:
p2 # # fetch 1,3 and 9,11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [201]:
p2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [205]:
 #fetch only 4 ,7 

array([4, 5, 6, 7])

In [207]:
p2[1] #  first row

array([4, 5, 6, 7])

In [208]:
p2[1,::3] # second columns

array([4, 7])

In [213]:
p2 # fetch 1,2,3 and 5,6,7 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [214]:
p2[0:2,1::]

array([[1, 2, 3],
       [5, 6, 7]])

In [215]:
 #fetch 1,3 and 5,7 
p2 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [219]:
p2[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [218]:
p2[0:2, 1::2]

array([[1, 3],
       [5, 7]])

# Slicing in 3D 

In [220]:
p3 = np.arange(27).reshape(3,3,3) 
p3 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [221]:
p3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [222]:
p3[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [226]:
p3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [229]:
p3[0,1,:] #EXPLANATION : 0 represnts first matrix , 1 represents second row , (:) means total

array([3, 4, 5])

In [237]:
p3 #Fetch 2 numpy array ,middle column ---> 10,13,16 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [231]:
p3[1] 

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [238]:
p3[1,:,1] # EXPLANATION : 1 respresnts middle column , (:) all columns , 1 represnts middle column 

array([10, 13, 16])

In [240]:
# Fetch 3 array--->22,23,25,26 
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [267]:
p3[2]  # last row 


array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [268]:
p3[2,1:,]  # last two rows

array([[21, 22, 23],
       [24, 25, 26]])

In [269]:
p3[2,1:,1:]  # last two columns

array([[22, 23],
       [25, 26]])

In [285]:
 # Fetch o, 2, 18 , 20 
p3 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [286]:
p3[0::2]  # for arrays 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [287]:
p3[0::2,0] # for first row

array([[ 0,  1,  2],
       [18, 19, 20]])

In [288]:
p3[0::2,0,::2] # for columns

array([[ 0,  2],
       [18, 20]])

# Iterating 

In [290]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [292]:
for i in p1:
    print (i)

0
1
2
3
4
5
6
7
8
9


In [293]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [294]:
for i in p2:
    print(i)


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [295]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [296]:
for i in p3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


print all items in 3D using nditer ---- > first convert in to 1D and applying Loop 

In [297]:
for i in np.nditer(p3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping 
 
Transpose ---> Converts rows in to clumns ad columns into rows

In [298]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [302]:
np.shape(p2)

(3, 4)

In [307]:
p5 = np.transpose(p2)
p5

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [308]:
np.shape(p5)

(4, 3)

In [309]:
p5.T

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Ravel 
 
Converting any dimensions to 1D 

In [311]:
p1,p2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [313]:
p2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [316]:
p5.ravel, p5

(<function ndarray.ravel>,
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]))

# Stacking 
 
Stacking is the concept of joining arrays in NumPy. Arrays having the same dimensions can be 
stacked 

In [317]:
w1 = np.arange(12).reshape(3,4)
w2 = np.arange(12,24).reshape(3,4)

In [319]:
w1, w2 , w1 +w2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]))

In [323]:
l= np.hstack((w1,w2))
l

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [324]:
np.shape(l)

(3, 8)

In [326]:
m =np.hstack((w2,w1))
m

array([[12, 13, 14, 15,  0,  1,  2,  3],
       [16, 17, 18, 19,  4,  5,  6,  7],
       [20, 21, 22, 23,  8,  9, 10, 11]])

In [328]:
o =np.vstack((w1,w2))
o

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting 
 
its opposite of Stacking 

In [333]:
w1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [334]:
np.hsplit(w1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [340]:
o
np.hsplit(o,4), np.hsplit(o,2)

([array([[ 0],
         [ 4],
         [ 8],
         [12],
         [16],
         [20]]),
  array([[ 1],
         [ 5],
         [ 9],
         [13],
         [17],
         [21]]),
  array([[ 2],
         [ 6],
         [10],
         [14],
         [18],
         [22]]),
  array([[ 3],
         [ 7],
         [11],
         [15],
         [19],
         [23]])],
 [array([[ 0,  1],
         [ 4,  5],
         [ 8,  9],
         [12, 13],
         [16, 17],
         [20, 21]]),
  array([[ 2,  3],
         [ 6,  7],
         [10, 11],
         [14, 15],
         [18, 19],
         [22, 23]])])

In [336]:
np.vsplit(o,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

# Numpy Arrays Vs Python Sequences 
    NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original. 
 
 
    The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences. A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. 

In [341]:
#Speed of List Vs Numpy 