In [4]:
import numpy as np

In [5]:
np.__version__

'2.3.5'

# What is Numpy? 
    NumPy is the fundamental package for scientific computing in Python. 
 
 
    It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types 

# Creating Numpy array 

In [8]:
np.array([2,4,56,422,32,1]) # iD array

array([  2,   4,  56, 422,  32,   1])

In [9]:
a = np.array([2,4,56,422,32,1]) # Vector
a

array([  2,   4,  56, 422,  32,   1])

In [10]:
type(a)

numpy.ndarray

In [14]:
# 2D array ( Matrix) using list
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# 2D array using tuple
np.array(([1,2,3],[4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
#  3 D ---- # Tensor 
np.array(([1,2,3,4],[5,6,6,7],[8,9,3,2]))

array([[1, 2, 3, 4],
       [5, 6, 6, 7],
       [8, 9, 3, 2]])

# dtype 
The desired data-type for the array. If not given, then the type willbe determined as the 
minimum type required to hold the objects in thesequence. 

In [19]:
np.array([11,23,44], dtype= float)

array([11., 23., 44.])

In [21]:
np.array([11,23,0], dtype= bool)  # Here True becoz , python treats Non -zero

array([ True,  True, False])

In [22]:
np.array((2.5,3,15), dtype = complex)

array([ 2.5+0.j,  3. +0.j, 15. +0.j])

# Numpy Arrays Vs Python Sequences 
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). 
Changing the size of an ndarray will create a new array and delete the original. 
The elements in a NumPy array are all required to be of the same data type, and thus will be 
the same size in memory. 
NumPy arrays facilitate advanced mathematical and other types of operations on large 
numbers of data. Typically, such operations are executed more efficiently and with less code 
than is possible using Python’s built-in sequences. 
A growing plethora of scientific and mathematical Python-based packages are using NumPy 
arrays; though these typically support Python-sequence input, they convert such input to 
NumPy arrays prior to processing, and they often output NumPy arrays. 

 # 1.Arrange
 arange can be called with a varying number of positional arguments

In [26]:
np.arange(5,15) # 5-included , 15 - last one got excluded 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
np.arange(0,20,2) #strides ---> Alternate numbers 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# 2. reshape 

In [30]:
np.arange(1,11) # with our reshaping 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
np.arange(1,11).reshape(2,5) # converted 2 rows and 5 columns 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
np.arange(1,11).reshape(5,2) # converted 5 rows and 2 columns 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# ones & Zeros

In [37]:
np.ones(2 )

array([1., 1.])

In [38]:
np.ones(5, dtype = int) # 1D array with 5 elements of dtype of integer.

array([1, 1, 1, 1, 1])

In [39]:
np.ones([2,5],dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [40]:
np.zeros((5,2),dtype = int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [42]:
# Another Type ---> random() 
np.random((2,5))

TypeError: 'module' object is not callable

In [45]:
np.random.random((2,5), datatype = int)

TypeError: random() got an unexpected keyword argument 'datatype'

In [55]:
np.random.random((2,5)) # first random is module and second one is Function()

array([[0.38474806, 0.49347104, 0.36550222, 0.86514395, 0.36536961],
       [0.03741203, 0.49464171, 0.55537864, 0.5800917 , 0.01901501]])

In [53]:
## np.random.randint((4,15)) # Randint will give any 4 numbers between 0 to 15

array([ 2, 12], dtype=int32)

# linspace

In [56]:
np.linspace(-10,10)

array([-10.        ,  -9.59183673,  -9.18367347,  -8.7755102 ,
        -8.36734694,  -7.95918367,  -7.55102041,  -7.14285714,
        -6.73469388,  -6.32653061,  -5.91836735,  -5.51020408,
        -5.10204082,  -4.69387755,  -4.28571429,  -3.87755102,
        -3.46938776,  -3.06122449,  -2.65306122,  -2.24489796,
        -1.83673469,  -1.42857143,  -1.02040816,  -0.6122449 ,
        -0.20408163,   0.20408163,   0.6122449 ,   1.02040816,
         1.42857143,   1.83673469,   2.24489796,   2.65306122,
         3.06122449,   3.46938776,   3.87755102,   4.28571429,
         4.69387755,   5.10204082,   5.51020408,   5.91836735,
         6.32653061,   6.73469388,   7.14285714,   7.55102041,
         7.95918367,   8.36734694,   8.7755102 ,   9.18367347,
         9.59183673,  10.        ])

In [57]:
np.linspace(-10,10,10)  # here: lower range,upper range ,number of items to gen

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [59]:
np.linspace(2,15,10)

array([ 2.        ,  3.44444444,  4.88888889,  6.33333333,  7.77777778,
        9.22222222, 10.66666667, 12.11111111, 13.55555556, 15.        ])

# identity 
indentity matrix is that diagonal items will be ones and evrything will be zeros 

In [60]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
np.identity(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [62]:
np.identity(5, dtype = bool)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

# Array Attributes

In [69]:
import numpy as np
a1 = np.arange(5) 
print(a1)

[0 1 2 3 4]


In [72]:
a2 = np.arange(25, dtype = int).reshape(5,5) # Matrix
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
a3 = np.arange(16, dtype = complex).reshape(4,2,2) 3D array
a3

array([[[ 0.+0.j,  1.+0.j],
        [ 2.+0.j,  3.+0.j]],

       [[ 4.+0.j,  5.+0.j],
        [ 6.+0.j,  7.+0.j]],

       [[ 8.+0.j,  9.+0.j],
        [10.+0.j, 11.+0.j]],

       [[12.+0.j, 13.+0.j],
        [14.+0.j, 15.+0.j]]])

In [75]:
a1, a2 ,a3

(array([0, 1, 2, 3, 4]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 array([[[ 0.+0.j,  1.+0.j],
         [ 2.+0.j,  3.+0.j]],
 
        [[ 4.+0.j,  5.+0.j],
         [ 6.+0.j,  7.+0.j]],
 
        [[ 8.+0.j,  9.+0.j],
         [10.+0.j, 11.+0.j]],
 
        [[12.+0.j, 13.+0.j],
         [14.+0.j, 15.+0.j]]]))

In [76]:
a1.ndim, a2.ndim , a3.ndim  # ndim To findout given arrays number of dimensions 

(1, 2, 3)

In [77]:
a1.shape , a2.shape, a3.shape  # Shape gives each item consist of no.of rows and np.of column 

((5,), (5, 5), (4, 2, 2))

In [79]:
a1.size, a2.size, a3.size #size gives number of items 

(5, 25, 16)

In [80]:
a1.itemsize, a2.itemsize,a3.itemsize #tem size Memory occupied by the item 

(8, 8, 16)

In [81]:
a1, a2, a3

(array([0, 1, 2, 3, 4]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 array([[[ 0.+0.j,  1.+0.j],
         [ 2.+0.j,  3.+0.j]],
 
        [[ 4.+0.j,  5.+0.j],
         [ 6.+0.j,  7.+0.j]],
 
        [[ 8.+0.j,  9.+0.j],
         [10.+0.j, 11.+0.j]],
 
        [[12.+0.j, 13.+0.j],
         [14.+0.j, 15.+0.j]]]))

In [82]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype) # dtype of the give array

int64
int64
complex128


In [ ]:
#Changing Data Type

In [88]:
a2.astype(float)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [91]:
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [86]:
a2.dtype

dtype('int64')

In [92]:
#astype 
 
x = np.array([33, 22, 2.5]) 
x 

array([33. , 22. ,  2.5])

In [95]:
x.astype(int)

array([33, 22,  2])

# Array Operations

In [96]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1, a2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [97]:
a1+a2 # Vector Opearions

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [98]:
a1-a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [99]:
a2-a1

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [100]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [101]:
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

a1**2

In [102]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [103]:
a1/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [104]:
a1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

# relational Operators 
The relational operators are also known as comparison operators, their main function is to 
return either a true or false based on the value of operands

In [107]:
a1 > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [108]:
a1<2

array([[ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

# Array Functions

In [109]:
k1 =np.random.random((3,3))
k1

array([[0.55674484, 0.17227496, 0.7759212 ],
       [0.55155137, 0.13680158, 0.52864997],
       [0.31341158, 0.84815143, 0.90826494]])

In [112]:
k1= np.round(k1*100)
k1

array([[56., 17., 78.],
       [55., 14., 53.],
       [31., 85., 91.]])

In [113]:
np.max(k1)

np.float64(91.0)

In [114]:
np.min(k1)

np.float64(14.0)

In [115]:
np.amax(k1)

np.float64(91.0)

In [116]:
np.sum(k1)

np.float64(480.0)

In [117]:
np.prod(k1)

np.float64(726641433117600.0)